### ISSUE TITLE
Strategies for more reasonable diffs (live demo with some slides)

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/2023-chop-training#14]
This live demo will cover strategies for making unreasonable diffs more reasonable, such as the following:

* Stacking pull requests (demo)
  * Forking model mostly doesn't mix with stacked PRs (slide)
* Cherry-picking commits (demo)
* Checking out individual files (slide)

The scope of this issue also includes writing instructor notes for the live demo portions to be placed in `instructor-notes`.

**Comment by jaclyn-taroni** [comment]
Looks good, @sjspielman ! I left some comments about the order of merging branches that are worth highlighting.

**Comment by sjspielman** [comment]
@jaclyn-taroni Ready for second round of review here! https://docs.google.com/presentation/d/14yNllNYqinzG5JrGUW31sIXSA49gQkRgmrXQJdXZ1AI/edit#slide=id.p

**Comment by jaclyn-taroni** [comment]
Looks good!
