### ISSUE TITLE
On being a pull request reviewer (slides)

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/2023-chop-training#15]
This issue tracks a set of slides on pull request reviewer responsibilities, such as the following:

* Giving constructive, empathetic feedback
* Explaining what you did to review the code (e.g., did you try to run it or read it?)
* Scope of the review depends on in-house criteria

**Comment by jaclyn-taroni** [comment]
[First draft of slides](https://docs.google.com/presentation/d/1BTQPS4xYnieDOVbf2ITS9ns1aiBGZCB8Gy1sQPa9oCs/edit?usp=sharing) for your review, @sjspielman! Thank you!

**Comment by sjspielman** [comment]
Slides look broadly good to me! Just one little text tweak I'd make, as I commented in the slides.
