### ISSUE TITLE
Initial review through getting code merged

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/2023-chop-training#17]
This lesson will cover topics that are relevant to the time period between when a review is returned through getting the code merged, which includes the following:

* Responding to review
  * Tip: filing new issues from comments 
* Dealing with merge conflicts (live demo)
  * VS Code
  * GitKraken 
* Deleting your branch, especially if stacking

**Comment by sjspielman** [comment]
@jaclyn-taroni Draft of slides is here for review! https://docs.google.com/presentation/d/1FoWxbh1aT4N4o4EVbnbx42hYNK-yY2CPIYoxa1wWSvw/edit#slide=id.p

In particular, please let me know you can think of other tips for leaving/responding to review that should be included here.

**Comment by jaclyn-taroni** [comment]
Most of my thoughts were on the responding to review side. I grabbed a few quotes from our handbook that I think would be good to cover (not necessarily the quotes themselves, but the ideas).

**Comment by sjspielman** [comment]
@jaclyn-taroni slides are ready for round 2 of review - https://docs.google.com/presentation/d/1FoWxbh1aT4N4o4EVbnbx42hYNK-yY2CPIYoxa1wWSvw/edit#slide=id.p

**Comment by jaclyn-taroni** [comment]
Made a couple cosmetic changes 👍🏻

**Comment by sjspielman** [comment]
Closed by this PR (in which I accidentally wrote closes #16, but this is #17!) https://github.com/AlexsLemonade/2023-chop-training/pull/58
