### ISSUE TITLE
Set up `Data Lab` computer account

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/2023-chop-training#39]
For a cleaner teaching experience, we should use a separate account on our computers.

- For everyone, make sure Zoom is installed and screen share is working
- For @sjspielman, a few more steps are needed!
  - [x] `GitKraken` is installed and repo is linked
  - [x]  `VS Code` is installed with any necessary extensions
  - [x] `git` is configured w/ 1Password (which may also need to be installed!)
    - Note to self: only log into CCDL account, not family account!
  - [x] (edit) R + RStudio are installed with packages `tidyverse`, `rmarkdown`, `broom`, `glue`, `here`, `palmerpenguins`,`umap`, but _not_ `patchwork`
  - [x] Make sure repo can be cloned, but delete any clone before workshop (re-clone as part of live demo)

**Comment by sjspielman** [comment]
I've set up my CCDL computer account and confirmed all applications are working as expected! I'm going to unassign myself from this issue now.

**Comment by jaclyn-taroni** [comment]
I've got a new account with Zoom installed with the correct permissions. I've turned off all the notifications. I'm logged into GitHub and the correct Google account for slides.
