### ISSUE TITLE
Git basics

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/2023-chop-training#4]
This issue tracks a lesson on git concepts we'll build on for the rest of the workshop. Specifically, we should cover:

* How much should go into a single commit
  * Using `git status`  and `git diff` as you go, before you commit
* Informative commit messages
* `.gitignore`
* `.gitkeep` (edit)
* (edit) show Blame view in github, for an `scpca` repo, to explain the concept of Blame view (demo)

**ETA:** Some of this will be slides, but there could be space for live demos with `git diff`, etc.

**Comment by sjspielman** [comment]
Just a comment to note that concepts planned in #3 are incorporated into these slides

> 
    Documentation also needs to be included in your repo. Managing the code with git is not sufficient.
    Writing and organizing your code with someone else in mind.
    Briefly: Issues can be used as a (light) project management tool.

**Comment by jaclyn-taroni** [comment]
You are absolutely not sorry about the pun.

**Comment by sjspielman** [comment]
> You are absolutely not sorry about the pun.

You see right through me!
