### ISSUE TITLE
Write demo code ahead of time

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/2023-chop-training#43]
To save some time during live demos, it would be helpful to write the some of actual code ahead of time for safe-keeping! This way we can directly copy/paste in during live demos. This will be only helpful for initial versions of scripts, i.e. not for modifying an already-existing script. We may want to break this up into multiple issues, but for now...

* [x] ~[`git` basics demo](https://github.com/AlexsLemonade/2023-chop-training/blob/cf7e4e46b5d1e151c1d74819733df887dd6adaa2/instructor-notes/git-basics.md): Histogram script without optparse~
  * Edit: Free check box since this was part of the pre-workshop setup 🙃 
* [x] [working with branches demo](https://github.com/AlexsLemonade/2023-chop-training/blob/cf7e4e46b5d1e151c1d74819733df887dd6adaa2/instructor-notes/working-with-branches.md): Filter to 2008 penguins
* [x] [working with branches demo](https://github.com/AlexsLemonade/2023-chop-training/blob/cf7e4e46b5d1e151c1d74819733df887dd6adaa2/instructor-notes/working-with-branches.md): Filter to Adelie penguins
* [x] [working with branches demo](https://github.com/AlexsLemonade/2023-chop-training/blob/cf7e4e46b5d1e151c1d74819733df887dd6adaa2/instructor-notes/working-with-branches.md): Count penguin species
* [x] [working with branches demo](https://github.com/AlexsLemonade/2023-chop-training/blob/cf7e4e46b5d1e151c1d74819733df887dd6adaa2/instructor-notes/working-with-branches.md): Summarize mass across penguin species
* [x] [stacking demo](https://github.com/AlexsLemonade/2023-chop-training/blob/cf7e4e46b5d1e151c1d74819733df887dd6adaa2/instructor-notes/stacking.md): Function to perform regression and return tidy output
* [x] [stacking demo](https://github.com/AlexsLemonade/2023-chop-training/blob/cf7e4e46b5d1e151c1d74819733df887dd6adaa2/instructor-notes/stacking.md): Run regression and export tidy result
* [x] [stacking demo](https://github.com/AlexsLemonade/2023-chop-training/blob/cf7e4e46b5d1e151c1d74819733df887dd6adaa2/instructor-notes/stacking.md): Function to make scatterplot
* [x] [stacking demo](https://github.com/AlexsLemonade/2023-chop-training/blob/cf7e4e46b5d1e151c1d74819733df887dd6adaa2/instructor-notes/stacking.md): Run scatterplot function and export PNG

Of course, I promptly thought of this _after_ we templatized the demo repo next door, but it's not too difficult to do that again if it might be better for re-use to add this content to `.live-demo-content/`. CC @jaclyn-taroni, thoughts?

**Comment by jaclyn-taroni** [comment]
I've added that, plus a little information in the `README.md` to the template repo: https://github.com/AlexsLemonade/git-code-review-live-demo

If you want to add more docs, @sjspielman, you will need to file a PR as I've now protected `main`.

**Comment by jaclyn-taroni** [comment]
I think we're done here!
