### ISSUE TITLE
Introduction to the workshop

### ISSUE THREAD

**Issue by jaclyn-taroni** [AlexsLemonade/2023-chop-training#6]
These slides should cover:

* Basic information about the instructors
* Housekeeping items like how to use the Slack channel
* What we will cover
* What we won't cover
* Overview of the schedule

**Comment by sjspielman** [comment]
@jaclyn-taroni I've started the slides here if you want to take it over at this point - https://docs.google.com/presentation/d/1NjaMd_dpjXjNFNDRb_atA_2iT4XwoTIJL9W5NBAL6Co/edit#slide=id.p

**Comment by sjspielman** [comment]
One final thing I'm wondering here @jaclyn-taroni  - do we want to add a bit about "why we chose to teach CLI git" here? In my view we're doing this since it's the most extensible, e.g. no GUIs on your external servers.

**Comment by jaclyn-taroni** [comment]
Sure. I'd also add that the vast majority of people that responded to the survey used the command line at least some of the time.
